-- Run in Supabase SQL Editor

create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text default '',
  price numeric not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists zones (
  id bigint generated by default as identity primary key,
  name text not null,
  fee numeric not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists settings (
  id int primary key default 1,
  business_name text not null default 'Нархан тэргүүн хүнс',
  phone text default '',
  qr_url text default '',
  min_order numeric not null default 0,
  orders_open boolean not null default true
);

create table if not exists orders (
  id text primary key,
  name text not null,
  phone text not null,
  address text not null,
  zone_id bigint,
  zone_name text,
  delivery_fee numeric not null default 0,
  delivery_time text,
  payment_ref text default '',
  subtotal numeric not null default 0,
  total numeric not null default 0,
  items jsonb not null default '[]'::jsonb,
  status text not null default 'Шинэ',
  payment_status text not null default 'Хүлээгдэж байна',
  created_at timestamptz not null default now()
);

insert into settings (id,business_name) values (1,'Нархан тэргүүн хүнс')
on conflict (id) do update set business_name=excluded.business_name;

insert into products (name,description,price,active)
select * from (values
 ('Үхрийн махтай бууз','20ш',28000,true),
 ('Хонины махтай бууз','20ш',30000,true),
 ('Гэр бүлийн багц','40ш',55000,true)
) as v(name,description,price,active)
where not exists (select 1 from products);

insert into zones (name,fee,active)
select * from (values
 ('Төвийн бүс',5000,true),
 ('Гадна бүс',8000,true)
) as v(name,fee,active)
where not exists (select 1 from zones);

-- Browser client must not read tables directly.
alter table products enable row level security;
alter table zones enable row level security;
alter table settings enable row level security;
alter table orders enable row level security;
